version: "3.3"
services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongodb_repl_data1:/data/db:z
    restart: always
  redis:
    hostname: redis
    container_name: redis
    image: redislabs/redismod
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - redisdb_repl_data1:/data
    restart: always
  elk:
    hostname: elk
    container_name: elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - "elasticsearch_repl_data1:/var/lib/elasticsearch"
  sql:
    hostname: sql
    container_name: sql
    image: 'mcr.microsoft.com/mssql/server'
    user: root
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=a123Aa123A
    volumes:
      - "sql_Data:/var/opt/mssql/data"
      - "sql_log:/var/opt/mssql/log"
      - "sql_secrets:/var/opt/mssql/secrets"
  prometheus:
    hostname: prometheus
    container_name: prometheus
    image: 'prom/prometheus:latest'
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    hostname: grafana
    container_name: grafana
    image: 'grafana/grafana:latest'
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: bitnami/rabbitmq
    restart: always
    environment:
     RABBITMQ_DEFAULT_USER: rabbit
     RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
  backup:
    hostname: backup
    container_name: backup
    image: 'jareware/docker-volume-backup:2.6.0'
    environment:
      SCP_HOST: 192.168.1.2
      SCP_USER: root
      SCP_DIRECTORY: /path/to/backups
    volumes:
      - sql_Data:/backup/sql_Data/_data:ro
      - ./backups:/archive
  cloudbeaver:
    image: dbeaver/cloudbeaver:${APP_VERSION}
    container_name: "${APP_NAME}"
    restart: always
    ports:
      - '$APP_HTTP_PORT:8978'
    volumes: 
      - cloudbeaver:/opt/cloudbeaver/workspace   
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./Users/ajeetraina/data/redisinsight:/db 
  eventstore.db:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
volumes:
  mongodb_repl_data1:
    external: true
  redisdb_repl_data1:
    external: true
  elasticsearch_repl_data1:
    external: true
  sql_Data:
    external: true
  sql_log:
    external: true
  sql_secrets:
    external: true
  prometheus-data:
    external: true
  grafana-data:
    external: true
  rabbitmq_data:
    external: true
  cloudbeaver:
    external: true
  eventstore-volume-data:
  eventstore-volume-logs: